version: "3.9"

services:
  api:
    build: .
    container_name: video-recommender-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    volumes:
      - .:/app

  redis:
    image: redis:7-alpine
    container_name: video-recommender-redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15-alpine
    container_name: video-recommender-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recommender
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
